---
# 运行样例：ansible-playbook /opt/auto-deployment/setup_cdh_cluster/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-25
# function: 配置本地的 yum 源，实际上是一个 web 服务
# CDH 官方配置本地仓库步骤：https://docs.cloudera.com/documentation/enterprise/6/6.2/topics/cm_ig_create_local_package_repo.html#internal_package_repo

  # 安装 httpd
  - name: 安装 httpd
    yum:
      name:
        - httpd
      state: present

  - name: 创建目录 /var/www/html/cloudera-repos/cm6
    file:
      path: /var/www/html/cloudera-repos/cm6
      state: directory
      mode: '0755'

  - name: 启动 httpd
    service:
      name: httpd
      state: started


  - name: 拷贝 cloudera-manager-agent-xxx.rpm 文件到本地仓库
    command: cp '{{paths.package}}/{{packages.cloudera_manager_agent}}' /var/www/html/cloudera-repos/cm6

  - name: 拷贝 cloudera-manager-daemons-xxx.rpm 文件到本地仓库
    command: cp '{{paths.package}}/{{packages.cloudera_manager_daemons}}' /var/www/html/cloudera-repos/cm6

  - name: 拷贝 cloudera-manager-server-xxx.rpm 文件到本地仓库
    command: cp '{{paths.package}}/{{packages.cloudera_manager_server}}' /var/www/html/cloudera-repos/cm6

  - name: 拷贝 cloudera-manager-server-db-xxx.rpm 文件到本地仓库
    command: cp '{{paths.package}}/{{packages.cloudera_manager_server_db}}' /var/www/html/cloudera-repos/cm6

  - name: 安装 createrepo 命令
    yum:
      name:
        - createrepo
      state: present

  # createrepo 在创建本地 yum 源时使用
  - name: 创建 repo 目录
    command: createrepo /var/www/html/cloudera-repos/cm6
