---
# 运行样例：ansible-playbook /opt/auto-deployment/cdh-setup/org/iconsider/cdh/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-18
# function: 自动部署 mysql server

  # 安装 MySQL Driver
  - name: 安装 MySQL Driver
    command: rm -rf /usr/share/java/mysql-connector-java.jar; cp {{paths.package}}/mysql-connector-java-*.jar /usr/share/java/mysql-connector-java.jar;

  # 安装 mysql 源
  - name: 安装 mysql 源
    yum:
      name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      state: present

  # 安装 mysql server
  - name: 安装 mysql server
    yum:
      name: mysql-server
      state: present

  # 备份 /etc/my.cnf
  - name: 判断 /etc/my.cnf 是否存在
    stat:
      path: /etc/my.cnf
    register: mysql_config

  - name: 备份 /etc/my.cnf
    command: mv /etc/my.cnf /etc/my_bak.cnf
    when: mysql_config.stat.exists

  # 复制新 my.cnf 到 /etc 下
  - name: 复制新 my.cnf 到 /etc 下
    command: mv '{{paths.package}}/my.cnf' /etc/

  - name: 启动 mysql server
    service:
      name: mysqld
      state: started

  # 构建 CDH 集群组件数据库
  - name: 删除列表中的数据库
    mysql_db:
      name:
        - scm
        - amon
        - rman
        - hive
        - sentry
        - nav
        - navms
        - oozie
        - hue
        - test
      state: absent

  # 构建 CDH 集群组件数据库
  - name: 创建列表中的数据库
    mysql_db:
      name: scm
      encoding: utf8
      state: present

  # todo 待测试
  - name: scm 下所有表的权限开放给 scm 用户
    mysql_user:
      name: scm
      password: scm_default_pwd
      priv: 'scm.*:ALL'
      state: present


