---
# 运行样例：ansible-playbook /opt/auto-deployment/setup_cdh_cluster/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-23
# function: 自动部署 Python 2 环境

  # 下载 pip
  # 参阅  https://pip.pypa.io/en/stable/installing/
  - name: 安装 pip 20.1.1
    # 国外源速度比较慢可以指定使用国内源命令
    shell: python "{{paths.package}}/get-pip.py" -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

    # 安装 pymysql
  - name: 安装 pymysql
    shell: pip install pymysql

