---
# 运行样例：ansible-playbook /opt/auto-deployment/cdh-setup/org/iconsider/cdh/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-18
# function: 自动配置 linux 系统环境

  # 1.1 关闭防火墙
  # https://docs.ansible.com/ansible/latest/modules/firewalld_module.html#firewalld-module
  - name: 关闭防火墙
    service:
      name: firewalld
      state: stopped
      enabled: no

  # 1.2 关闭 selinux
  - name: 转成 Permissive 宽容模式
    shell: "setenforce 0"
    failed_when: false

  - name: 关闭 selinux
    replace:
      path: /etc/selinux/config
      regexp: '^SELINUX=enforcing'
      replace: 'SELINUX=disabled'

  # 1.3 安装常见工具
  # 注意：单独一个 task 安装 epel，epel-release 是包丰富的第三方源，缺少 epel 其他“安装常见工具命令”组件可能会安装失败
  - name: 安装 yum 源
    yum:
      name:
        - epel-release
      state: present

  - name: 安装常见工具命令
    yum:
      name:
        - htop
        - iotop
        - vim
        - sysstat
        - iftop
        - screen
      state: present

  # todo，更新 yum 现有程序


  # 1.4 创建安装包目录
  # https://docs.ansible.com/ansible/latest/modules/file_module.html#examples
  - name: 创建基础目录
    file:
      path: /opt/setup_cdh
      state: directory
      mode: '0755'

  # 1.5 分发安装包、驱动
  # https://docs.ansible.com/ansible/latest/modules/copy_module.html#id5
  - name: 分发安装包、驱动到计算节点
    copy:
      src: /opt/setup_cdh
      dest: /opt/
      owner: root
      group: root
      mode: u=rwx,g=rwx,o=rwx
