---
# 运行样例：ansible-playbook /opt/auto-deployment/setup_cdh_cluster/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-18
# function: 自动部署搭建 CDH 集群
# 版本要求:
# CDH 6.2.0
# Ansible 2.7.2
# Python 2.7.5

# python 模块要求：
# PyMySQL - 安装命令：pip install pymysql


- hosts: master_node
  # 开启debug
  gather_facts: F
  vars:
    # 各种路径
    paths:
      package: /opt/setup_cdh
    # 各种密码
    password:
      mysql: 123456
    # 各种组件安装包
    packages:
      cloudera_manager_agent: cloudera-manager-agent-6.2.0-968826.el7.x86_64.rpm
      cloudera_manager_daemons: cloudera-manager-daemons-6.2.0-968826.el7.x86_64.rpm
      cloudera_manager_server: cloudera-manager-server-6.2.0-968826.el7.x86_64.rpm
      cloudera_manager_server_db: cloudera-manager-server-db-2-6.2.0-968826.el7.x86_64.rpm
#      mysql_server: mysql-community-server-5.7.30-1.el7.x86_64.rpm

  remote_user: root

  tasks:
    # 1.配置本地仓库服务
    - include: ./component/setup_local_repository.yml



## 1.0 基础配置
## hosts 组配置 /etc/ansible/hosts
#- hosts: all_node
#  # 开启debug
#  gather_facts: F
#  vars:
#    # 各种路径
#    paths:
#      package: /opt/setup_cdh
#    # 各种密码
#    password:
#      mysql: 123456
#    # 各种组件安装包
#    packages:
#      java: jdk-8u261-linux-x64.tar.gz
#      scala: scala-2.13.0-M4.tgz
#      mysql_driver: mysql-connector-java-5.1.47.jar
##      mysql_client: mysql-community-client-5.7.30-1.el7.x86_64.rpm
#
#    # 各种链接
#    url:
#      cloudera_baseurl: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/
#      cloudera_baseurl_local: http://192.168.220.31/cloudera-repos/cm6/
#
#  remote_user: root
#
#  tasks:
#    # 1.配置 linux 系统环境
##    - include: ./component/setup_system_env.yml
#
#    # 2.配置 Java 环境
#    #    - include: ./component/setup_java_env.yml
#
#    # 3.配置 Scala 环境
#    #    - include: ./component/setup_scala_env.yml
#
#    # 4.配置 Python 环境
#    #    - include: ./component/setup_python_env.yml
#
#    # 5.配置 mysql server
#    #    - include: ./component/setup_mysql_server.yml
#
#    # 安装 yum 源文件
##    - include: ./component/setup_local_yum.yml
#
#    # 7.配置 cloudera manager server
##    - include: ./component/setup_cloudera_manager_server.yml
#
#    # last:重启节点





# 测试
# hosts 组配置 /etc/ansible/hosts
- hosts: cdh5
  # 开启debug
  gather_facts: F
  vars:
    # 各种路径
    paths:
      package: /opt/setup_cdh
    # 各种密码，注意新版 mysql 对密码有严格要求
    password:
      mysql: SuperMan2020#h
      scm: SuperMan2020#h
      amon: SuperMan2020#h
      rman: SuperMan2020#h
      hive: SuperMan2020#h
      sentry: SuperMan2020#h
      nav: SuperMan2020#h
      navms: SuperMan2020#h
      oozie: SuperMan2020#h
      hue: SuperMan2020#h
    # 各种组件安装包
    packages:
      java: jdk-8u261-linux-x64.tar.gz
      scala: scala-2.13.0-M4.tgz
      mysql_driver: mysql-connector-java-5.1.47.jar
      # todo, 注释掉 server
#      mysql_server: mysql-community-server-5.7.30-1.el7.x86_64.rpm
#      mysql_client: mysql-community-client-5.7.30-1.el7.x86_64.rpm

#      cloudera_manager_agent: cloudera-manager-agent-6.2.0-968826.el7.x86_64.rpm
#      cloudera_manager_daemons: cloudera-manager-daemons-6.2.0-968826.el7.x86_64.rpm
#      cloudera_manager_server: cloudera-manager-server-6.2.0-968826.el7.x86_64.rpm
#      cloudera_manager_server_db: cloudera-manager-server-db-2-6.2.0-968826.el7.x86_64.rpm
    # 各种链接
    url:
      cloudera_baseurl: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/
      cloudera_baseurl_local: http://192.168.220.31/cloudera-repos/cm6/

  remote_user: root

  tasks:
    # 1.配置 linux 系统环境
    - include: ./component/setup_system_env.yml

    # 2.配置 Java 环境
    - include: ./component/setup_java_env.yml

    # 3.配置 Scala 环境
    - include: ./component/setup_scala_env.yml

    # 4.配置 Python 环境
    - include: ./component/setup_python_env.yml

    # todo, 5.配置 mysql，分一个 client 出来
    - include: ./component/setup_mysql_server.yml

    # 安装 yum 源文件
    - include: ./component/setup_local_yum.yml

    # 7.配置 cloudera manager server
    - include: ./component/setup_cloudera_manager_server.yml

    # last:重启节点
